#!/usr/bin/env python3
"""One-time configuration setup for XDigest.

Run this script once to configure all settings:
- Environment variables
- API keys (stored securely in macOS Keychain)
- Email settings
- Follow accounts

Usage:
    python setup_config.py
"""

import os
import sys
import keyring
from pathlib import Path


def get_input(prompt: str, default: str = None, required: bool = True) -> str:
    """Get user input with optional default value."""
    if default:
        prompt = f"{prompt} [{default}]"
    prompt += ": "

    while True:
        value = input(prompt).strip()
        if not value and default:
            return default
        if value or not required:
            return value
        print("This field is required. Please enter a value.")


def get_multiline_input(prompt: str) -> str:
    """Get multiline input (for follow accounts)."""
    print(f"\n{prompt}")
    print("Enter account usernames (one per line, without @).")
    print("Press Enter twice when done:")

    accounts = []
    while True:
        line = input().strip()
        if not line:
            if accounts:
                break
            print("Please enter at least one account.")
            continue
        # Remove @ if user included it
        account = line.lstrip('@')
        accounts.append(account)

    return ','.join(accounts)


def main():
    print("=" * 60)
    print("XDigest Configuration Setup")
    print("=" * 60)
    print("\nThis script will help you configure XDigest.")
    print("All sensitive data (API keys, passwords) will be stored")
    print("securely in macOS Keychain.\n")

    # Create .env file path
    env_file = Path(__file__).parent / '.env'

    # Collect configuration
    config = {}

    print("\n--- Email Settings ---")
    config['EMAIL_FROM'] = get_input("Your email address (sender)")
    config['EMAIL_TO'] = get_input("Recipient email address", default=config['EMAIL_FROM'])
    config['SMTP_HOST'] = get_input("SMTP server", default="smtp.gmail.com")
    config['SMTP_PORT'] = get_input("SMTP port", default="587")

    print("\n--- SMTP Password ---")
    print("For Gmail, use an App Password (not your regular password):")
    print("https://support.google.com/accounts/answer/185833")
    smtp_password = get_input("SMTP password (will be stored in Keychain)")

    print("\n--- Gemini API Key ---")
    print("Get your API key from: https://aistudio.google.com/app/apikey")
    gemini_api_key = get_input("Gemini API key (will be stored in Keychain)")

    print("\n--- X (Twitter) Accounts to Follow ---")
    follow_accounts = get_multiline_input("Enter accounts to follow")
    config['FOLLOW_ACCOUNTS'] = follow_accounts

    print("\n--- Optional Settings ---")
    config['HEADLESS'] = get_input("Run browser in headless mode? (true/false)", default="true", required=False)
    config['DB_PATH'] = get_input("Database path", default="~/.xdigest/xdigest.db", required=False)
    config['LOG_PATH'] = get_input("Log directory", default="~/.xdigest/logs/", required=False)
    config['BROWSER_DATA_PATH'] = get_input("Browser data path", default="~/.xdigest/browser/", required=False)

    # Write .env file
    print("\n--- Saving Configuration ---")
    with open(env_file, 'w') as f:
        f.write("# XDigest Configuration\n")
        f.write("# Generated by setup_config.py\n\n")
        for key, value in config.items():
            if value:  # Only write non-empty values
                f.write(f"{key}={value}\n")

    print(f"✓ Configuration saved to: {env_file}")

    # Store secrets in Keychain
    print("\n--- Storing Secrets in Keychain ---")
    try:
        keyring.set_password('xdigest', 'smtp_password', smtp_password)
        print("✓ SMTP password stored in Keychain")

        keyring.set_password('xdigest', 'gemini_api_key', gemini_api_key)
        print("✓ Gemini API key stored in Keychain")
    except Exception as e:
        print(f"✗ Error storing secrets: {e}")
        sys.exit(1)

    # Create directories
    print("\n--- Creating Directories ---")
    db_path = Path(config.get('DB_PATH', '~/.xdigest/xdigest.db')).expanduser()
    log_path = Path(config.get('LOG_PATH', '~/.xdigest/logs/')).expanduser()
    browser_path = Path(config.get('BROWSER_DATA_PATH', '~/.xdigest/browser/')).expanduser()

    db_path.parent.mkdir(parents=True, exist_ok=True)
    log_path.mkdir(parents=True, exist_ok=True)
    browser_path.mkdir(parents=True, exist_ok=True)

    print(f"✓ Created: {db_path.parent}")
    print(f"✓ Created: {log_path}")
    print(f"✓ Created: {browser_path}")

    print("\n" + "=" * 60)
    print("✓ Configuration Complete!")
    print("=" * 60)
    print("\nYou can now run XDigest:")
    print("  python main.py --use-chrome")
    print("\nTo reconfigure, run this script again:")
    print("  python setup_config.py")
    print()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nConfiguration cancelled.")
        sys.exit(1)
